@BASE_URL=http://localhost:3000

### Create a new product
POST {{BASE_URL}}/products
Content-Type: application/json

{
  "name": "Product Out of Stock",
  "description": "This product is currently out of stock",
  "price": 0.99,
  "stock": 0
}

### Get all products

GET {{BASE_URL}}/products

### Get a product by ID
GET {{BASE_URL}}/products/1

### Update a product by ID
PATCH {{BASE_URL}}/products/2
Content-Type: application/json

{
  "stock": 50
}

### Delete a product by ID
DELETE {{BASE_URL}}/products/1