@BASE_URL=http://localhost:3001

### Health Check
GET {{BASE_URL}}/health

### Create Cart
POST {{BASE_URL}}/cart
Content-Type: application/json

{
  "customerId": 1,
  "productId": 3,
  "quantity": 2
}

### Get Cart

### Update Cart

### Delete Cart

### Create Order

### Get Orders

### Get Order by ID

### Delete Order by ID