@BASE_URL=http://localhost:3001

### Health Check
GET {{BASE_URL}}/health

### Create Cart
POST {{BASE_URL}}/cart
Content-Type: application/json

{
  "customerId": 1,
  "productId": 1,
  "quantity": 1
}

### Get Cart
GET {{BASE_URL}}/cart
Content-Type: application/json

{
  "customerId": 1
}

### Update Cart
PATCH {{BASE_URL}}/cart/1
Content-Type: application/json

{
  "quantity": 3
}

### Delete Cart Item
DELETE {{BASE_URL}}/cart/1

### Create Order
POST {{BASE_URL}}/order

### Get Orders

### Get Order by ID

### Delete Order by ID